const LIMIT_MIN_MAX = {
  EVENT_DESCRIPTION_MAX: 100,
  EVENT_DESCRIPTION_MIN: 10,
  EVENT_LOCATION_MAX: 100,
  EVENT_LOCATION_MIN: 5,
  EVENT_POSTER_URL_MAX: 400,
  EVENT_POSTER_URL_MIN: 4,
  EVENT_TITLE_MAX: 50,
  EVENT_TITLE_MIN: 6,

  IMAGE_LENGTH_MAX: 400,
  IMAGE_LENGTH_MIN: 1,

  NAME_LENGTH_MAX: 100,
  NAME_LENGTH_MIN: 3,

  PASSWORD_LENGTH_MAX: 24,
  PASSWORD_LENGTH_MIN: 8,
  STRONG_PASSWORD_MIN_LENGTH: 8,
  STRONG_PASSWORD_MIN_LOWERCASE: 1,
  STRONG_PASSWORD_MIN_NUMBER: 1,
  STRONG_PASSWORD_MIN_SYMBOL: 1,
  STRONG_PASSWORD_MIN_UPPERCASE: 1
} as const
export default LIMIT_MIN_MAX
